<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MailboxDocumentsItemHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['_id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['_id']->setValue($document, $return);
            $hydratedData['_id'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['uid']) || (! empty($this->class->fieldMappings['uid']['nullable']) && array_key_exists('uid', $data))) {
            $value = $data['uid'];
            if ($value !== null) {
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['uid']->setValue($document, $return);
            $hydratedData['uid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['sender']) || (! empty($this->class->fieldMappings['sender']['nullable']) && array_key_exists('sender', $data))) {
            $value = $data['sender'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['sender']->setValue($document, $return);
            $hydratedData['sender'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['subject']) || (! empty($this->class->fieldMappings['subject']['nullable']) && array_key_exists('subject', $data))) {
            $value = $data['subject'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['subject']->setValue($document, $return);
            $hydratedData['subject'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['message']) || (! empty($this->class->fieldMappings['message']['nullable']) && array_key_exists('message', $data))) {
            $value = $data['message'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['message']->setValue($document, $return);
            $hydratedData['message'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['time_sent']) || (! empty($this->class->fieldMappings['time_sent']['nullable']) && array_key_exists('time_sent', $data))) {
            $value = $data['time_sent'];
            if ($value !== null) {
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['time_sent']->setValue($document, $return);
            $hydratedData['time_sent'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['read']) || (! empty($this->class->fieldMappings['read']['nullable']) && array_key_exists('read', $data))) {
            $value = $data['read'];
            if ($value !== null) {
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['read']->setValue($document, $return);
            $hydratedData['read'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['archived']) || (! empty($this->class->fieldMappings['archived']['nullable']) && array_key_exists('archived', $data))) {
            $value = $data['archived'];
            if ($value !== null) {
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['archived']->setValue($document, $return);
            $hydratedData['archived'] = $return;
        }
        return $hydratedData;
    }
}