<?php

namespace Mailbox\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends DocumentRepository
{
    public function getArchivedQueryBuilder()
    {
        return $this->createQueryBuilder()
                ->field('archived')->equals(true);
    }
    
    public function read($uid)
    {
        return $this->createQueryBuilder()
            ->findAndUpdate()
            ->returnNew()
            ->field('uid')->equals($uid)
            ->field('read')->set(true)
            ->getQuery()
            ->execute();
    }
    
    public function archive($uid)
    {
        return $this->createQueryBuilder()
            ->findAndUpdate()
            ->returnNew()
            ->field('uid')->equals($uid)
            ->field('archived')->set(true)
            ->getQuery()
            ->execute();
    }
}
