Mailbox\Documents\Item:
  db: mailbox
  collection: items
  type: document
  repositoryClass: Mailbox\Repository\ItemRepository
  fields:
    _id:
      type: id
      id: true
      strategy: AUTO
    uid:
      type: integer
    sender:
      type: string
    subject:
      type: string
    message: 
      type: string
    time_sent:
      type: timestamp
    read:
      type: boolean
    archived:
      type: boolean
  