<?php

namespace Mailbox\Documents;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-05 at 23:36:16.
 */
class ItemTest extends TestCase {

    /**
     * @var Item
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Item;
    }

    public function testJsonSerializeReturnsArray() {
        $result = $this->object->jsonSerialize();
        $this->assertInternalType('array', $result);
        $this->assertArrayHasKey('uid', $result);
        $this->assertArrayHasKey('sender', $result);
        $this->assertArrayHasKey('subject', $result);
        $this->assertArrayHasKey('message', $result);
        $this->assertArrayHasKey('time_sent', $result);
        $this->assertArrayHasKey('read', $result);
        $this->assertArrayHasKey('archived', $result);
    }

}
